In [2]:
import tensorflow as tf

[[1. 0. 0. 0.]
 [0. 0. 0. 1.]]


In [26]:
labels = ['100_pct', '75_pct', '50_pct']
res = tf.one_hot(indices=[0, 2, 2, 0, 1], depth=3)


In [27]:
with tf.Session() as sess:
    print (sess.run(res))

[[1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]]
